import pathlib

PROJECT_NAME = 'SPLM2'
PROJECT_DIR = pathlib.Path.home() / PROJECT_NAME

DATASETS_DIR = PROJECT_DIR / 'datasets'

EXPERIMENTS_DIR = PROJECT_DIR / 'experiments'
EXPERIMENTS_RESULTS_DIR = EXPERIMENTS_DIR / 'results'
EXPERIMENTS_TEMPLATES_DIR = EXPERIMENTS_DIR / 'templates'
