import pathlib

PROJECT_NAME = 'SPLM'
PROJECT_DIR = pathlib.Path.home() / PROJECT_NAME

DATASETS_DIR = PROJECT_DIR / 'datasets'

EXPERIMENTS_DIR = PROJECT_DIR / 'experiments'
EXPERIMENTS_RESULTS_DIR = EXPERIMENTS_DIR / 'results'
EXPERIMENTS_BATCHES_DIR = EXPERIMENTS_DIR / 'batches'
EXPERIMENTS_TEMPLATES_DIR = EXPERIMENTS_BATCHES_DIR / 'templates'
